### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by XiaoHaoPan** [nhduong/guided_demoireing_net#1]
PackagesNotFoundError: The following packages are not available from current channels

Thank you very much for your work, but this environment seems to be difficult to configure, these packages seem to be too many, and errors occur every time. Do I need to document the installation one by one according to the requirements?

**Comment by nhduong** [comment]
Thanks for your interest in our work.

In general, you don't have to install all the packages listed in requirements.txt. A default environment with PyTorch, Hugging Face Accelerator should work. Additional packages might be required, but they can be installed easily by following developers' instructions.

**Comment by XiaoHaoPan** [comment]
Thanks, I found that after installing **PyTorch** I only need to install these to be able to test.
**pip install accelerate**
**pip install natsort**
**pip install scikit-image**
**pip install lpips**
**pip install opencv-python**
**pip install tensorboard**
**pip install six**

After that, I tested AIM's dataset, but the metrics were all 0 and I didn't understand what was wrong.

![image](https://github.com/nhduong/guided_demoireing_net/assets/127167436/9a37439c-59c1-44ee-990a-7b69c47926e5)

Here's my dataset structure.

guided_demoireing_net
- dataset
  - train
    - clear
    - moire
  - val
    - clear
    - moire

**Comment by XiaoHaoPan** [comment]
I found the same issue in the training state
![image](https://github.com/nhduong/guided_demoireing_net/assets/127167436/6ca5cd9b-37c3-4ce2-ad33-dffc1df7c417)

**Comment by nhduong** [comment]
Could you please show me the values of `args` for training and testing? They are given by line #185 in the code.

**Comment by XiaoHaoPan** [comment]
This is testing.
![image](https://github.com/nhduong/guided_demoireing_net/assets/127167436/920cc53b-0551-4530-ae4c-fc89031a7169)

This is training.
![image](https://github.com/nhduong/guided_demoireing_net/assets/127167436/9b074f4c-df14-46f2-9643-dc5ee892ad4c)

**Comment by nhduong** [comment]
Thank you. They look just right to me.
- For training, it is expected to NOT compute PSNR and SSIM since `dont_calc_mets_at_all=True` to speed up the training process.
- For testing, the PSNR and SSIM should be calculated. I think there might be errors with
https://github.com/nhduong/guided_demoireing_net/blob/3eb8fb1c3dd45f4a9bf4ca38acbce91b48135672/main.py#L772
Could you please add `print(e)` before
https://github.com/nhduong/guided_demoireing_net/blob/3eb8fb1c3dd45f4a9bf4ca38acbce91b48135672/main.py#L774
and run the test again to see if there are any issues?

**Comment by XiaoHaoPan** [comment]
Yes, it seems to be the problem here, after my troubleshooting, I found that the parameters of the SSIM calculation function in the skimage library have changed.
    
https://github.com/nhduong/guided_demoireing_net/blob/3eb8fb1c3dd45f4a9bf4ca38acbce91b48135672/main.py#L1101

I changed it to `ssim = ski_ssim(mt1, mi1, data_range=mt1.max() - mt1.min(),channel_axis=2）`.

The test has been successfully completed, thank you very much for your help.

![image](https://github.com/nhduong/guided_demoireing_net/assets/127167436/8436d234-cffd-47fe-995e-a4dc47c5f9b2)

**Comment by nhduong** [comment]
You are welcome
