### ISSUE TITLE
LCD Moire dataset

### ISSUE THREAD

**Issue by DYY512** [nhduong/guided_demoireing_net#2]
Hello, could I get the LCD Moire dataset from you? There is no way to download it now.

**Comment by nhduong** [comment]
We are sorry to hear that. It is better for you to contact the authors of the dataset directly first. If the problem cannot be solved, please let us know.

**Comment by DYY512** [comment]
> We are sorry to hear that. It is better for you to contact the authors of the dataset directly first. If the problem cannot be solved, please let us know.

Thank you very much for your reply. I registered on the aim2019 website and signed up for the competition. Maybe I can get the download link after I pass it.

**Comment by nhduong** [comment]
You're welcome.

**Comment by DYY512** [comment]
Hi, I'm sorry to bother you again. 
I’ve registered for the AIM2019 demoire competition and passed the review, but the download link provided in "Get Data" is invalid, showing “Not Found. The requested URL was not found on this server.” This issue was reported in the forum three weeks ago, but it still hasn’t been resolved. 
Could I ask you to share the dataset with me? Thank you so much! My email is 2200432037@email.szu.edu.cn

![codalab](https://github.com/user-attachments/assets/04872cef-59e2-4dcf-9821-31a26a076972)

**Comment by Shawn-CodeDev** [comment]
Hello author, we are also having the same problem. Could you please share a copy of the dataset with us, thank you!My email:gary_144@outlook.com
