### ISSUE TITLE
Can't install requiremwnts.txt

### ISSUE THREAD

**Issue by Zerycii** [nhduong/guided_demoireing_net#3]
![image](https://github.com/user-attachments/assets/89582ba0-211f-4e5f-be56-7881589850fe)
Always have this error even I change the chanel.

**Comment by nhduong** [comment]
Sorry for the inconvenience. You might want to consider one of the following approaches:
- Creating a _basic_ environment and installing additional packages based on the errors you get.
- Running the code with Docker. First, you pull a Docker image for PyTorch, e.g., [pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel](https://hub.docker.com/layers/pytorch/pytorch/2.0.1-cuda11.7-cudnn8-devel/images/sha256-4f66166dd757752a6a6a9284686b4078e92337cd9d12d2e14d2d46274dfa9048?context=explore), then you can install additional packages.

**Comment by Zerycii** [comment]
> Sorry for the inconvenience. You might want to consider one of the following approaches:
> 
> * Creating a _basic_ environment and installing additional packages based on the errors you get.
> * Running the code with Docker. First, you pull a Docker image for PyTorch, e.g., [pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel](https://hub.docker.com/layers/pytorch/pytorch/2.0.1-cuda11.7-cudnn8-devel/images/sha256-4f66166dd757752a6a6a9284686b4078e92337cd9d12d2e14d2d46274dfa9048?context=explore), then you can install additional packages.

thanks for your reply and outstanding work! I try to install them one by one,But I don't know how to insatll cuml and apex.I tried many ways but no effect.Could you help me and if I don't install cuml and apex, will be a error?

**Comment by nhduong** [comment]
Thank you for your interest in our work.

We used apex to speed up the training with automatic mixed precision. So without apex, the code is still supposed to run normally. All you need to do is modifying `mixed_precision: fp16` to `mixed_precision: no` in [default_config.yaml](https://github.com/nhduong/guided_demoireing_net/blob/3eb8fb1c3dd45f4a9bf4ca38acbce91b48135672/default_config.yaml#L7).

If the above options do not help, you might want to take a look at NVIDIA DGL containers, e.g., [https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-05.html](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-05.html), which also include apex.

**Comment by Zerycii** [comment]
/home/lmh/.local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
>>> Tensorboard logs saved to: /data1/lzq/results_guided/outputs/spl/Moire/[spl]_[Moire]_[rev_1]_[2024-10-24]_[23.11.26.736310]_[GPU_1]_[amax]/tb/train
>>> Tensorboard logs saved to: /data1/lzq/results_guided/outputs/spl/Moire/[spl]_[Moire]_[rev_1]_[2024-10-24]_[23.11.26.736310]_[GPU_1]_[amax]/tb/val
Traceback (most recent call last):
  File "/home/lmh/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lmh/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/lmh/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/lmh/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/anaconda3/bin/python', 'main.py', '--affine', '--l1loss', '--adaloss', '--perloss', '--dont_calc_mets_at_all', '--log2file', '--data_path', '/data1/lzq/Moire_512', '--data_name', 'Moire', '--train_dir', 'train', '--test_dir', 'val', '--moire_dir', 'moire', '--clean_dir', 'clear', '--batch_size', '2', '--T_0', '50', '--epochs', '100', '--init_weights']' returned non-zero exit status 1.
 Exucuse me. I always meet this error.My python is  Python 3.8.13 and torch/torchvision version is as following.I install torchvision and torch many times but the error is still here. 
 
![image](https://github.com/user-attachments/assets/ce82036d-a108-46a8-ad81-2e41bb2f6648)

**Comment by nhduong** [comment]
Since --log2file is set, could you please take a look at the .log file in the output folder for more information?

**Comment by Zerycii** [comment]
> Since --log2file is set, could you please take a look at the .log file in the output folder for more information?

thanks for your help. I use the instruction to train model:python main.py --affine --l1loss --adaloss --perloss --dont_calc_mets_at_all --log2file \
    --data_path "path_to/aim2019_demoireing_track1" \
    --data_name aim --train_dir "train" --test_dir "val" --moire_dir "moire" --clean_dir "clear" \
    --batch_size 2 --T_0 50 --epochs 200 --init_weights.
    but threre is another question:
    
![image](https://github.com/user-attachments/assets/424ae36a-c77d-4fa0-ac83-bd32a53c7e94)
when I finished the train,I found that  PSNR= 0  SSIM =0

**Comment by nhduong** [comment]
That is because --dont_calc_mets_at_all was used to skip evaluation steps (which heavily rely on CPU) to speed up the training. You can follow the evaluation step in the instructions to get PSNR and SSIM.

**Comment by Zerycii** [comment]
thanks very much. I'm grateful your heartwarm help and your outstanding work!!!
