### ISSUE TITLE
Request for LCDMoiré Dataset (Baidu or Google Drive Link)

### ISSUE THREAD

**Issue by wscffaa** [nhduong/guided_demoireing_net#4]
Dear Author,

I hope you are doing well. I am currently working on a demoireing project and found your work on the “Guided DeMoireing Network” to be incredibly valuable. However, I have run into an issue where the original competition website’s download link for the LCDMoiré dataset is no longer available.

Could you kindly provide an alternative download link for the dataset, such as through Baidu Netdisk or Google Drive? It would be a tremendous help for my research and experimentation with your network.

I sincerely appreciate your time and assistance and look forward to your response.

Best regards

**Comment by nhduong** [comment]
Thank you for your interest in our work.

Please contact the authors of the dataset first (via email for example) since I do not have the right to distribute the data. If it does not help, please leave your email here so that I can get back to you.

**Comment by wscffaa** [comment]
I have already contacted the original dataset authors, but unfortunately, the download link on the official website is no longer available. 

My email is: wscffaa@gmail.com

Thank you again for your assistance and contribution!
